spring:
  datasource:
    url: jdbc:mysql://192.168.12.156:3306/gitlab_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: handhand
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
gitlab:
  url: "http://git.staging.saas.hand-china.com"
  privateToken: "kEXZHti27y8zJDyWahaC"
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 1
feign:
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000
logging:
  level:
    io.choerodon.event.consumer: debug